### ISSUE TITLE
New release of ihaskell-diagrams that is compatible with current ihaskell-display

### ISSUE THREAD

**Issue by sternenseemann** [IHaskell/IHaskell#1378]
The changes from #1359 have been released to hackage for `ihaskell-display`, but not `ihaskell-diagrams`, meaning that the latest versions of the two packages don't build together at the moment.

**Comment by FPtje** [comment]
`ihaskell-diagrams` is currently marked as broken in Nixpkgs due to this issue:

https://github.com/NixOS/nixpkgs/blob/5ca8e2e9e1fa5e66a749b39261ad6bd0e07bc87f/pkgs/development/haskell-modules/hackage-packages.nix#L158855-L158871

@sternenseemann I see you've removed it from the `ihaskell` package. Thanks for the quick fix!

https://github.com/NixOS/nixpkgs/pull/196169

This does mean that rendering diagrams is broken in notebooks that use `ihaskell` from nixpkgs.

**Comment by jamesdbrock** [comment]
Rendering with __ihaskell-diagrams__ does work, after #1379 . You can run the example notebook for __ihaskell-diagrams__ if you click the __launch binder__ button here https://github.com/IHaskell/ihaskell-notebook

__haskell-diagrams__ is also working in the `result/bin/jupyterlab` built by the `flake.nix` with `nix build .#ihaskell-env-display`.

So we should figure out how to get it working in the `ihaskell` from nixpkgs.

**Comment by djacu** [comment]
If I understand things correctly, it is because nixpkgs pulls `ihaskell-diagrams` from hackage. The version in hackage is 0.3.2.1 which still has `switchToTmpDir` which was replaced in #1359.

I believe if you bump the version and release a new version to hackage, then we can update nixpkgs. Specifically, it will need a new `version` and `sha256`, and the `broken` attribute will need to be marked as `false`.

**Comment by mknorps** [comment]
Is there a blocker to release `ihaskell-diagrams` on hackage? It would be great to be able to use this package in `ihaskell` from nixpkgs. We are using in in [monad-bayes](https://hackage.haskell.org/package/monad-bayes) documentation notebooks.

**Comment by vaibhavsagar** [comment]
I've released [`ihaskell-diagrams-0.4.0.0`](https://hackage.haskell.org/package/ihaskell-diagrams-0.4.0.0).
